// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BuildCause build cause
// swagger:model BuildCause
type BuildCause struct {

	// material revisions
	MaterialRevisions []*MaterialRevision `json:"material_revisions"`

	// trigger message
	TriggerMessage string `json:"trigger_message,omitempty"`
}

// Validate validates this build cause
func (m *BuildCause) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMaterialRevisions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildCause) validateMaterialRevisions(formats strfmt.Registry) error {

	if swag.IsZero(m.MaterialRevisions) { // not required
		return nil
	}

	for i := 0; i < len(m.MaterialRevisions); i++ {
		if swag.IsZero(m.MaterialRevisions[i]) { // not required
			continue
		}

		if m.MaterialRevisions[i] != nil {
			if err := m.MaterialRevisions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("material_revisions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BuildCause) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildCause) UnmarshalBinary(b []byte) error {
	var res BuildCause
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
