// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewHistoryParams creates a new HistoryParams object
// with the default values initialized.
func NewHistoryParams() *HistoryParams {
	var ()
	return &HistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHistoryParamsWithTimeout creates a new HistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHistoryParamsWithTimeout(timeout time.Duration) *HistoryParams {
	var ()
	return &HistoryParams{

		timeout: timeout,
	}
}

// NewHistoryParamsWithContext creates a new HistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewHistoryParamsWithContext(ctx context.Context) *HistoryParams {
	var ()
	return &HistoryParams{

		Context: ctx,
	}
}

// NewHistoryParamsWithHTTPClient creates a new HistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHistoryParamsWithHTTPClient(client *http.Client) *HistoryParams {
	var ()
	return &HistoryParams{
		HTTPClient: client,
	}
}

/*HistoryParams contains all the parameters to send to the API endpoint
for the history operation typically these are written to a http.Request
*/
type HistoryParams struct {

	/*App
	  app id.

	*/
	App string
	/*ID
	  instance id.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the history params
func (o *HistoryParams) WithTimeout(timeout time.Duration) *HistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the history params
func (o *HistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the history params
func (o *HistoryParams) WithContext(ctx context.Context) *HistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the history params
func (o *HistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the history params
func (o *HistoryParams) WithHTTPClient(client *http.Client) *HistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the history params
func (o *HistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApp adds the app to the history params
func (o *HistoryParams) WithApp(app string) *HistoryParams {
	o.SetApp(app)
	return o
}

// SetApp adds the app to the history params
func (o *HistoryParams) SetApp(app string) {
	o.App = app
}

// WithID adds the id to the history params
func (o *HistoryParams) WithID(id int64) *HistoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the history params
func (o *HistoryParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *HistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app
	if err := r.SetPathParam("app", o.App); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
