// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/riksa/gonkka/pkg/gocd/models"
)

// InstanceReader is a Reader for the Instance structure.
type InstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewInstanceOK creates a InstanceOK with default headers values
func NewInstanceOK() *InstanceOK {
	return &InstanceOK{}
}

/*InstanceOK handles this case with default header values.

Instance request success
*/
type InstanceOK struct {
	Payload *models.InstanceResponse
}

func (o *InstanceOK) Error() string {
	return fmt.Sprintf("[GET /pipelines/{app}/instance/{id}][%d] instanceOK  %+v", 200, o.Payload)
}

func (o *InstanceOK) GetPayload() *models.InstanceResponse {
	return o.Payload
}

func (o *InstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InstanceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
